\@LN{0}{16}
\@LN{100}{31}
\@LN{101}{31}
\@LN{102}{31}
\@LN{103}{31}
\@LN{104}{31}
\@LN{105}{31}
\@LN{106}{31}
\@LN{107}{31}
\@LN{108}{31}
\@LN{109}{31}
\@LN{10}{18}
\@LN{110}{31}
\@LN{111}{31}
\@LN{112}{31}
\@LN{113}{31}
\@LN{114}{31}
\@LN{115}{31}
\@LN{116}{31}
\@LN{117}{31}
\@LN{118}{31}
\@LN{119}{31}
\@LN{11}{18}
\@LN{120}{31}
\@LN{121}{31}
\@LN{122}{32}
\@LN{123}{32}
\@LN{124}{32}
\@LN{125}{32}
\@LN{126}{32}
\@LN{127}{32}
\@LN{128}{32}
\@LN{129}{32}
\@LN{12}{18}
\@LN{130}{32}
\@LN{131}{32}
\@LN{132}{32}
\@LN{133}{32}
\@LN{134}{32}
\@LN{135}{32}
\@LN{136}{32}
\@LN{137}{32}
\@LN{138}{32}
\@LN{139}{32}
\@LN{13}{18}
\@LN{140}{32}
\@LN{141}{32}
\@LN{142}{32}
\@LN{143}{32}
\@LN{144}{32}
\@LN{145}{32}
\@LN{146}{32}
\@LN{147}{32}
\@LN{148}{32}
\@LN{149}{32}
\@LN{14}{18}
\@LN{150}{32}
\@LN{151}{32}
\@LN{152}{32}
\@LN{153}{32}
\@LN{154}{33}
\@LN{155}{34}
\@LN{156}{34}
\@LN{157}{36}
\@LN{158}{36}
\@LN{159}{36}
\@LN{15}{18}
\@LN{160}{36}
\@LN{161}{36}
\@LN{162}{38}
\@LN{163}{38}
\@LN{164}{38}
\@LN{165}{38}
\@LN{166}{38}
\@LN{167}{38}
\@LN{168}{38}
\@LN{169}{38}
\@LN{16}{20}
\@LN{17}{20}
\@LN{18}{20}
\@LN{19}{20}
\@LN{1}{16}
\@LN{20}{20}
\@LN{21}{20}
\@LN{22}{20}
\@LN{23}{22}
\@LN{24}{22}
\@LN{25}{22}
\@LN{26}{22}
\@LN{27}{22}
\@LN{28}{22}
\@LN{29}{24}
\@LN{2}{16}
\@LN{30}{24}
\@LN{31}{24}
\@LN{32}{24}
\@LN{33}{26}
\@LN{34}{26}
\@LN{35}{26}
\@LN{36}{26}
\@LN{37}{26}
\@LN{38}{28}
\@LN{39}{28}
\@LN{3}{16}
\@LN{40}{28}
\@LN{41}{28}
\@LN{42}{28}
\@LN{43}{28}
\@LN{44}{28}
\@LN{45}{28}
\@LN{46}{28}
\@LN{47}{28}
\@LN{48}{28}
\@LN{49}{28}
\@LN{4}{16}
\@LN{50}{28}
\@LN{51}{28}
\@LN{52}{28}
\@LN{53}{28}
\@LN{54}{28}
\@LN{55}{29}
\@LN{56}{29}
\@LN{57}{29}
\@LN{58}{29}
\@LN{59}{29}
\@LN{5}{16}
\@LN{60}{29}
\@LN{61}{29}
\@LN{62}{29}
\@LN{63}{29}
\@LN{64}{29}
\@LN{65}{29}
\@LN{66}{29}
\@LN{67}{29}
\@LN{68}{29}
\@LN{69}{29}
\@LN{6}{16}
\@LN{70}{29}
\@LN{71}{29}
\@LN{72}{29}
\@LN{73}{29}
\@LN{74}{30}
\@LN{75}{30}
\@LN{76}{30}
\@LN{77}{30}
\@LN{78}{30}
\@LN{79}{30}
\@LN{7}{16}
\@LN{80}{30}
\@LN{81}{30}
\@LN{82}{30}
\@LN{83}{30}
\@LN{84}{30}
\@LN{85}{30}
\@LN{86}{30}
\@LN{87}{30}
\@LN{88}{30}
\@LN{89}{30}
\@LN{8}{16}
\@LN{90}{30}
\@LN{91}{30}
\@LN{92}{30}
\@LN{93}{31}
\@LN{94}{31}
\@LN{95}{31}
\@LN{96}{31}
\@LN{97}{31}
\@LN{98}{31}
\@LN{99}{31}
\@LN{9}{16}
\@setckpt{Chapter1/chapter1}{
\@setckpt{Chapter2/chapter2}{
\@setckpt{Chapter3/chapter3}{
\@setckpt{Chapter4/chapter4}{
\@setckpt{Chapter5/chapter5}{
\@setckpt{Chapter6/chapter6}{
\@setckpt{Sections/Abstract/abstract}{
\@setckpt{Sections/Acknowledgement/acknowledgement}{
\@setckpt{Sections/Appendix1/appendix1}{
\@setckpt{Sections/Appendix2/appendix2}{
\@setckpt{Sections/Appendix3/appendix3}{
\@setckpt{Sections/Declaration/declaration}{
\@setckpt{Sections/Dedication/dedication}{
\@writefile{lof}{\addvspace {10\p@ }}
\@writefile{lof}{\addvspace {10\p@ }}
\@writefile{lof}{\addvspace {10\p@ }}
\@writefile{lof}{\addvspace {10\p@ }}
\@writefile{lof}{\addvspace {10\p@ }}
\@writefile{lof}{\addvspace {10\p@ }}
\@writefile{lof}{\addvspace {10\p@ }}
\@writefile{lof}{\addvspace {10\p@ }}
\@writefile{lof}{\addvspace {10\p@ }}
\@writefile{lot}{\addvspace {10\p@ }}
\@writefile{lot}{\addvspace {10\p@ }}
\@writefile{lot}{\addvspace {10\p@ }}
\@writefile{lot}{\addvspace {10\p@ }}
\@writefile{lot}{\addvspace {10\p@ }}
\@writefile{lot}{\addvspace {10\p@ }}
\@writefile{lot}{\addvspace {10\p@ }}
\@writefile{lot}{\addvspace {10\p@ }}
\@writefile{lot}{\addvspace {10\p@ }}
\@writefile{toc}{\contentsline {chapter}{Appendix \numberline {A}Inertial Measurement Units}{13}{Appendix.a.A}}
\@writefile{toc}{\contentsline {chapter}{Appendix \numberline {B}How to install \LaTeX  }{21}{Appendix.a.B}}
\@writefile{toc}{\contentsline {chapter}{Appendix \numberline {C}Installing the CUED class file}{23}{Appendix.a.C}}
\@writefile{toc}{\contentsline {chapter}{List of figures}{xiii}{chapter*.5}}
\@writefile{toc}{\contentsline {chapter}{List of tables}{xv}{chapter*.6}}
\@writefile{toc}{\contentsline {chapter}{\numberline {1}Introduction}{1}{chapter.1}}
\@writefile{toc}{\contentsline {chapter}{\numberline {2}Movement Variability}{3}{chapter.2}}
\@writefile{toc}{\contentsline {chapter}{\numberline {3}Techniques to measure human movement variability}{5}{chapter.3}}
\@writefile{toc}{\contentsline {chapter}{\numberline {4}Experiments}{7}{chapter.4}}
\@writefile{toc}{\contentsline {chapter}{\numberline {5}Automatic Classification}{9}{chapter.5}}
\@writefile{toc}{\contentsline {chapter}{\numberline {6}Conclusion}{11}{chapter.6}}
\@writefile{toc}{\contentsline {section}{\numberline {1.1}Opening hook}{1}{section.1.1}}
\@writefile{toc}{\contentsline {section}{\numberline {1.2}Context}{1}{section.1.2}}
\@writefile{toc}{\contentsline {section}{\numberline {1.3}Gap in the literature}{1}{section.1.3}}
\@writefile{toc}{\contentsline {section}{\numberline {1.4}Research Questions}{1}{section.1.4}}
\@writefile{toc}{\contentsline {section}{\numberline {1.5}Argument}{1}{section.1.5}}
\@writefile{toc}{\contentsline {section}{\numberline {1.6}Outline of logic}{1}{section.1.6}}
\@writefile{toc}{\contentsline {section}{\numberline {2.1}Source of Variability in Human Movement}{3}{section.2.1}}
\@writefile{toc}{\contentsline {section}{\numberline {2.2}Sensors}{3}{section.2.2}}
\@writefile{toc}{\contentsline {section}{\numberline {2.3}Variability within and between persons}{3}{section.2.3}}
\@writefile{toc}{\contentsline {section}{\numberline {2.4}Variability for simple and complex activities}{3}{section.2.4}}
\@writefile{toc}{\contentsline {section}{\numberline {3.1}Time-domain}{5}{section.3.1}}
\@writefile{toc}{\contentsline {section}{\numberline {3.2}Frequency-domain}{5}{section.3.2}}
\@writefile{toc}{\contentsline {section}{\numberline {3.3}Nonlinear dynamics domain}{5}{section.3.3}}
\@writefile{toc}{\contentsline {section}{\numberline {4.1}Dancing Salsa}{7}{section.4.1}}
\@writefile{toc}{\contentsline {section}{\numberline {4.2}Simple movements}{7}{section.4.2}}
\@writefile{toc}{\contentsline {section}{\numberline {4.3}Human-Humanoid Imitation}{7}{section.4.3}}
\@writefile{toc}{\contentsline {section}{\numberline {4.4}Group Activity in Human-Humanoid Imitation}{7}{section.4.4}}
\@writefile{toc}{\contentsline {section}{\numberline {5.1}Convolutional Neural Networks}{9}{section.5.1}}
\@writefile{toc}{\contentsline {section}{\numberline {5.2}Convolutional Neural Networks Using time-series}{9}{section.5.2}}
\@writefile{toc}{\contentsline {section}{\numberline {6.1}Short title}{11}{section.6.1}}
\@writefile{toc}{\contentsline {section}{\numberline {A.1}benchmark}{18}{section.a.A.1}}
\@writefile{toc}{\thispagestyle {empty}}
\AtEndDocument{\ifx\hyper@anchor\@undefined
\HyperFirstAtBeginDocument{\ifx\hyper@anchor\@undefined
\bibdata{References/references}
\bibstyle{apalike}
\citation{AAB95,Con90,LM65}
\citation{Aup91}
\citation{Rea85,Ancey1996}
\fi}
\fi}
\gdef\HyperFirstAtBeginDocument#1{#1}
\gdef\contentsline#1#2#3#4{\oldcontentsline{#1}{#2}{#3}}
\gdef\newlabel#1#2{\newlabelxx{#1}#2}
\gdef\newlabelxx#1#2#3#4#5#6{\oldnewlabel{#1}{{#2}{#3}}}
\global\let\hyper@last\relax 
\global\let\oldcontentsline\contentsline
\global\let\oldnewlabel\newlabel
\let\contentsline\oldcontentsline
\let\newlabel\oldnewlabel
\newlabel{section1.1}
\providecommand\HyField@AuxAddToCoFields[2]{}
\providecommand\HyField@AuxAddToFields[1]{}
\providecommand\HyperFirstAtBeginDocument{\AtBeginDocument}
\providecommand\hyper@newdestlabel[2]{}
\providecommand\hyper@newdestlabel[2]{}
\providecommand\hyper@newdestlabel[2]{}
\providecommand\hyper@newdestlabel[2]{}
\providecommand\hyper@newdestlabel[2]{}
\providecommand\hyper@newdestlabel[2]{}
\providecommand\hyper@newdestlabel[2]{}
\providecommand\hyper@newdestlabel[2]{}
\providecommand\hyper@newdestlabel[2]{}
\providecommand\hyper@newdestlabel[2]{}
\providecommand\hyper@newdestlabel[2]{}
\providecommand\hyper@newdestlabel[2]{}
\providecommand\hyper@newdestlabel[2]{}
\providecommand\hyper@newdestlabel[2]{}
\setcounter{@ppsaveapp}{0}
\setcounter{@ppsaveapp}{0}
\setcounter{@ppsaveapp}{0}
\setcounter{@ppsaveapp}{0}
\setcounter{@ppsaveapp}{0}
\setcounter{@ppsaveapp}{0}
\setcounter{@ppsaveapp}{0}
\setcounter{@ppsaveapp}{0}
\setcounter{@ppsaveapp}{0}
\setcounter{@ppsaveapp}{0}
\setcounter{@ppsaveapp}{0}
\setcounter{@ppsaveapp}{0}
\setcounter{@ppsaveapp}{0}
\setcounter{@ppsavesec}{0}
\setcounter{@ppsavesec}{0}
\setcounter{@ppsavesec}{0}
\setcounter{@ppsavesec}{0}
\setcounter{@ppsavesec}{0}
\setcounter{@ppsavesec}{0}
\setcounter{@ppsavesec}{0}
\setcounter{@ppsavesec}{0}
\setcounter{@ppsavesec}{0}
\setcounter{@ppsavesec}{0}
\setcounter{@ppsavesec}{6}
\setcounter{@ppsavesec}{6}
\setcounter{@ppsavesec}{6}
\setcounter{@pps}{0}
\setcounter{@pps}{0}
\setcounter{@pps}{0}
\setcounter{@pps}{0}
\setcounter{@pps}{0}
\setcounter{@pps}{0}
\setcounter{@pps}{0}
\setcounter{@pps}{0}
\setcounter{@pps}{0}
\setcounter{@pps}{0}
\setcounter{@pps}{1}
\setcounter{@pps}{1}
\setcounter{@pps}{1}
\setcounter{ContinuedFloat}{0}
\setcounter{ContinuedFloat}{0}
\setcounter{ContinuedFloat}{0}
\setcounter{ContinuedFloat}{0}
\setcounter{ContinuedFloat}{0}
\setcounter{ContinuedFloat}{0}
\setcounter{ContinuedFloat}{0}
\setcounter{ContinuedFloat}{0}
\setcounter{ContinuedFloat}{0}
\setcounter{ContinuedFloat}{0}
\setcounter{ContinuedFloat}{0}
\setcounter{ContinuedFloat}{0}
\setcounter{ContinuedFloat}{0}
\setcounter{Hfootnote}{0}
\setcounter{Hfootnote}{0}
\setcounter{Hfootnote}{0}
\setcounter{Hfootnote}{0}
\setcounter{Hfootnote}{0}
\setcounter{Hfootnote}{0}
\setcounter{Hfootnote}{0}
\setcounter{Hfootnote}{0}
\setcounter{Hfootnote}{0}
\setcounter{Hfootnote}{0}
\setcounter{Hfootnote}{0}
\setcounter{Hfootnote}{0}
\setcounter{Hfootnote}{0}
\setcounter{Item}{0}
\setcounter{Item}{0}
\setcounter{Item}{0}
\setcounter{Item}{0}
\setcounter{Item}{0}
\setcounter{Item}{0}
\setcounter{Item}{0}
\setcounter{Item}{0}
\setcounter{Item}{0}
\setcounter{Item}{0}
\setcounter{Item}{0}
\setcounter{Item}{0}
\setcounter{Item}{0}
\setcounter{LN@truepage}{17}
\setcounter{LN@truepage}{19}
\setcounter{LN@truepage}{21}
\setcounter{LN@truepage}{23}
\setcounter{LN@truepage}{25}
\setcounter{LN@truepage}{27}
\setcounter{LN@truepage}{35}
\setcounter{LN@truepage}{37}
\setcounter{LN@truepage}{39}
\setcounter{LN@truepage}{3}
\setcounter{LN@truepage}{5}
\setcounter{LN@truepage}{7}
\setcounter{LN@truepage}{9}
\setcounter{NAT@ctr}{0}
\setcounter{NAT@ctr}{0}
\setcounter{NAT@ctr}{0}
\setcounter{NAT@ctr}{0}
\setcounter{NAT@ctr}{0}
\setcounter{NAT@ctr}{0}
\setcounter{NAT@ctr}{0}
\setcounter{NAT@ctr}{0}
\setcounter{NAT@ctr}{0}
\setcounter{NAT@ctr}{0}
\setcounter{NAT@ctr}{0}
\setcounter{NAT@ctr}{0}
\setcounter{NAT@ctr}{0}
\setcounter{bookmark@seq@number}{0}
\setcounter{bookmark@seq@number}{0}
\setcounter{bookmark@seq@number}{0}
\setcounter{bookmark@seq@number}{0}
\setcounter{bookmark@seq@number}{10}
\setcounter{bookmark@seq@number}{15}
\setcounter{bookmark@seq@number}{19}
\setcounter{bookmark@seq@number}{24}
\setcounter{bookmark@seq@number}{27}
\setcounter{bookmark@seq@number}{29}
\setcounter{bookmark@seq@number}{31}
\setcounter{bookmark@seq@number}{32}
\setcounter{bookmark@seq@number}{33}
\setcounter{chapter}{0}
\setcounter{chapter}{0}
\setcounter{chapter}{0}
\setcounter{chapter}{0}
\setcounter{chapter}{1}
\setcounter{chapter}{1}
\setcounter{chapter}{2}
\setcounter{chapter}{2}
\setcounter{chapter}{3}
\setcounter{chapter}{3}
\setcounter{chapter}{4}
\setcounter{chapter}{5}
\setcounter{chapter}{6}
\setcounter{enumiii}{0}
\setcounter{enumiii}{0}
\setcounter{enumiii}{0}
\setcounter{enumiii}{0}
\setcounter{enumiii}{0}
\setcounter{enumiii}{0}
\setcounter{enumiii}{0}
\setcounter{enumiii}{0}
\setcounter{enumiii}{0}
\setcounter{enumiii}{0}
\setcounter{enumiii}{0}
\setcounter{enumiii}{0}
\setcounter{enumiii}{0}
\setcounter{enumii}{0}
\setcounter{enumii}{0}
\setcounter{enumii}{0}
\setcounter{enumii}{0}
\setcounter{enumii}{0}
\setcounter{enumii}{0}
\setcounter{enumii}{0}
\setcounter{enumii}{0}
\setcounter{enumii}{0}
\setcounter{enumii}{0}
\setcounter{enumii}{0}
\setcounter{enumii}{0}
\setcounter{enumii}{0}
\setcounter{enumiv}{0}
\setcounter{enumiv}{0}
\setcounter{enumiv}{0}
\setcounter{enumiv}{0}
\setcounter{enumiv}{0}
\setcounter{enumiv}{0}
\setcounter{enumiv}{0}
\setcounter{enumiv}{0}
\setcounter{enumiv}{0}
\setcounter{enumiv}{0}
\setcounter{enumiv}{0}
\setcounter{enumiv}{0}
\setcounter{enumiv}{0}
\setcounter{enumi}{0}
\setcounter{enumi}{0}
\setcounter{enumi}{0}
\setcounter{enumi}{0}
\setcounter{enumi}{0}
\setcounter{enumi}{0}
\setcounter{enumi}{0}
\setcounter{enumi}{0}
\setcounter{enumi}{0}
\setcounter{enumi}{0}
\setcounter{enumi}{0}
\setcounter{enumi}{0}
\setcounter{enumi}{0}
\setcounter{equation}{0}
\setcounter{equation}{0}
\setcounter{equation}{0}
\setcounter{equation}{0}
\setcounter{equation}{0}
\setcounter{equation}{0}
\setcounter{equation}{0}
\setcounter{equation}{0}
\setcounter{equation}{0}
\setcounter{equation}{0}
\setcounter{equation}{0}
\setcounter{equation}{0}
\setcounter{equation}{0}
\setcounter{figure}{0}
\setcounter{figure}{0}
\setcounter{figure}{0}
\setcounter{figure}{0}
\setcounter{figure}{0}
\setcounter{figure}{0}
\setcounter{figure}{0}
\setcounter{figure}{0}
\setcounter{figure}{0}
\setcounter{figure}{0}
\setcounter{figure}{0}
\setcounter{figure}{0}
\setcounter{figure}{0}
\setcounter{footnote}{0}
\setcounter{footnote}{0}
\setcounter{footnote}{0}
\setcounter{footnote}{0}
\setcounter{footnote}{0}
\setcounter{footnote}{0}
\setcounter{footnote}{0}
\setcounter{footnote}{0}
\setcounter{footnote}{0}
\setcounter{footnote}{0}
\setcounter{footnote}{0}
\setcounter{footnote}{0}
\setcounter{footnote}{0}
\setcounter{linenumber}{0}
\setcounter{linenumber}{0}
\setcounter{linenumber}{0}
\setcounter{linenumber}{0}
\setcounter{linenumber}{10}
\setcounter{linenumber}{157}
\setcounter{linenumber}{162}
\setcounter{linenumber}{16}
\setcounter{linenumber}{170}
\setcounter{linenumber}{23}
\setcounter{linenumber}{29}
\setcounter{linenumber}{33}
\setcounter{linenumber}{38}
\setcounter{mpfootnote}{0}
\setcounter{mpfootnote}{0}
\setcounter{mpfootnote}{0}
\setcounter{mpfootnote}{0}
\setcounter{mpfootnote}{0}
\setcounter{mpfootnote}{0}
\setcounter{mpfootnote}{0}
\setcounter{mpfootnote}{0}
\setcounter{mpfootnote}{0}
\setcounter{mpfootnote}{0}
\setcounter{mpfootnote}{0}
\setcounter{mpfootnote}{0}
\setcounter{mpfootnote}{0}
\setcounter{page}{10}
\setcounter{page}{10}
\setcounter{page}{12}
\setcounter{page}{20}
\setcounter{page}{22}
\setcounter{page}{24}
\setcounter{page}{2}
\setcounter{page}{4}
\setcounter{page}{4}
\setcounter{page}{6}
\setcounter{page}{6}
\setcounter{page}{8}
\setcounter{page}{8}
\setcounter{paragraph}{0}
\setcounter{paragraph}{0}
\setcounter{paragraph}{0}
\setcounter{paragraph}{0}
\setcounter{paragraph}{0}
\setcounter{paragraph}{0}
\setcounter{paragraph}{0}
\setcounter{paragraph}{0}
\setcounter{paragraph}{0}
\setcounter{paragraph}{0}
\setcounter{paragraph}{0}
\setcounter{paragraph}{0}
\setcounter{paragraph}{0}
\setcounter{parentequation}{0}
\setcounter{parentequation}{0}
\setcounter{parentequation}{0}
\setcounter{parentequation}{0}
\setcounter{parentequation}{0}
\setcounter{parentequation}{0}
\setcounter{parentequation}{0}
\setcounter{parentequation}{0}
\setcounter{parentequation}{0}
\setcounter{parentequation}{0}
\setcounter{parentequation}{0}
\setcounter{parentequation}{0}
\setcounter{parentequation}{0}
\setcounter{part}{0}
\setcounter{part}{0}
\setcounter{part}{0}
\setcounter{part}{0}
\setcounter{part}{0}
\setcounter{part}{0}
\setcounter{part}{0}
\setcounter{part}{0}
\setcounter{part}{0}
\setcounter{part}{0}
\setcounter{part}{0}
\setcounter{part}{0}
\setcounter{part}{0}
\setcounter{section@level}{0}
\setcounter{section@level}{0}
\setcounter{section@level}{0}
\setcounter{section@level}{0}
\setcounter{section@level}{1}
\setcounter{section@level}{1}
\setcounter{section@level}{1}
\setcounter{section@level}{1}
\setcounter{section@level}{1}
\setcounter{section@level}{1}
\setcounter{section@level}{1}
\setcounter{section@level}{1}
\setcounter{section@level}{1}
\setcounter{section}{0}
\setcounter{section}{0}
\setcounter{section}{0}
\setcounter{section}{0}
\setcounter{section}{0}
\setcounter{section}{0}
\setcounter{section}{1}
\setcounter{section}{1}
\setcounter{section}{2}
\setcounter{section}{3}
\setcounter{section}{4}
\setcounter{section}{4}
\setcounter{section}{6}
\setcounter{subfigure}{0}
\setcounter{subfigure}{0}
\setcounter{subfigure}{0}
\setcounter{subfigure}{0}
\setcounter{subfigure}{0}
\setcounter{subfigure}{0}
\setcounter{subfigure}{0}
\setcounter{subfigure}{0}
\setcounter{subfigure}{0}
\setcounter{subfigure}{0}
\setcounter{subfigure}{0}
\setcounter{subfigure}{0}
\setcounter{subfigure}{0}
\setcounter{subparagraph}{0}
\setcounter{subparagraph}{0}
\setcounter{subparagraph}{0}
\setcounter{subparagraph}{0}
\setcounter{subparagraph}{0}
\setcounter{subparagraph}{0}
\setcounter{subparagraph}{0}
\setcounter{subparagraph}{0}
\setcounter{subparagraph}{0}
\setcounter{subparagraph}{0}
\setcounter{subparagraph}{0}
\setcounter{subparagraph}{0}
\setcounter{subparagraph}{0}
\setcounter{subsection}{0}
\setcounter{subsection}{0}
\setcounter{subsection}{0}
\setcounter{subsection}{0}
\setcounter{subsection}{0}
\setcounter{subsection}{0}
\setcounter{subsection}{0}
\setcounter{subsection}{0}
\setcounter{subsection}{0}
\setcounter{subsection}{0}
\setcounter{subsection}{0}
\setcounter{subsection}{0}
\setcounter{subsection}{0}
\setcounter{subsubsection}{0}
\setcounter{subsubsection}{0}
\setcounter{subsubsection}{0}
\setcounter{subsubsection}{0}
\setcounter{subsubsection}{0}
\setcounter{subsubsection}{0}
\setcounter{subsubsection}{0}
\setcounter{subsubsection}{0}
\setcounter{subsubsection}{0}
\setcounter{subsubsection}{0}
\setcounter{subsubsection}{0}
\setcounter{subsubsection}{0}
\setcounter{subsubsection}{0}
\setcounter{subtable}{0}
\setcounter{subtable}{0}
\setcounter{subtable}{0}
\setcounter{subtable}{0}
\setcounter{subtable}{0}
\setcounter{subtable}{0}
\setcounter{subtable}{0}
\setcounter{subtable}{0}
\setcounter{subtable}{0}
\setcounter{subtable}{0}
\setcounter{subtable}{0}
\setcounter{subtable}{0}
\setcounter{subtable}{0}
\setcounter{table}{0}
\setcounter{table}{0}
\setcounter{table}{0}
\setcounter{table}{0}
\setcounter{table}{0}
\setcounter{table}{0}
\setcounter{table}{0}
\setcounter{table}{0}
\setcounter{table}{0}
\setcounter{table}{0}
\setcounter{table}{0}
\setcounter{table}{0}
\setcounter{table}{0}
}
}
}
}
}
}
}
}
}
}
}
}
}
